/*
 * Copyright (c) 2003, 2025, Oracle and/or its affiliates. All rights reserved.
 * Copyright (c) 2014, 2020, Red Hat Inc. All rights reserved.
 * Copyright (c) 2020, 2023, Huawei Technologies Co., Ltd. All rights reserved.
 * Copyright (c) 2026, IA-64 port contributors. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 *
 */

#include "asm/macroAssembler.inline.hpp"
#include "gc/shared/barrierSet.hpp"
#include "gc/shared/barrierSetAssembler.hpp"
#include "interp_masm_ia64.hpp"
#include "interpreter/interpreter.hpp"
#include "interpreter/interpreterRuntime.hpp"
#include "logging/log.hpp"
#include "oops/arrayOop.hpp"
#include "oops/markWord.hpp"
#include "oops/method.hpp"
#include "oops/methodData.hpp"
#include "oops/resolvedFieldEntry.hpp"
#include "oops/resolvedIndyEntry.hpp"
#include "oops/resolvedMethodEntry.hpp"
#include "prims/jvmtiExport.hpp"
#include "prims/jvmtiThreadState.hpp"
#include "runtime/basicLock.hpp"
#include "runtime/frame.inline.hpp"
#include "runtime/javaThread.hpp"
#include "runtime/safepointMechanism.hpp"
#include "runtime/sharedRuntime.hpp"
#include "utilities/powerOfTwo.hpp"

// Derived from cpu/riscv/interp_masm_riscv.cpp. The register mapping is
// riscv x10 -> Rtos (r8), f10 -> Ftos (f8), xbcp/xlocals/esp/xcpool/xmethod
// -> Rbcp/Rlocals/Resp/Rcpool/Rmethod, and riscv's x11-x15 scratch -> r20-r24
// (j_rarg0-4, free inside the interpreter). Departures that are about IA-64
// rather than renaming are marked "IA-64:".

// Interpreter-internal scratch (see the mapping note above).
static constexpr Register Rscratch1 = r20;
static constexpr Register Rscratch2 = r21;
static constexpr Register Rscratch3 = r22;
static constexpr Register Rscratch4 = r23;

void InterpreterMacroAssembler::narrow(Register result) {
  assert_different_registers(result, Rscratch1, Rscratch2);
  // Get method->_constMethod->_result_type
  get_method(Rscratch1);
  ld8(Rscratch1, Address(Rscratch1, Method::const_offset()));
  ld1(Rscratch1, Address(Rscratch1, ConstMethod::result_type_offset()));

  Label done, notBool, notByte, notChar;

  // common case first
  cmp_eq_imm(ptmp0, ptmp1, T_INT, Rscratch1);
  br_cond(done, ptmp0);

  // mask integer result to narrower return type.
  cmp_eq_imm(ptmp0, ptmp1, T_BOOLEAN, Rscratch1);
  br_cond(notBool, ptmp1);
  and_imm(result, 0x1, result);
  j(done);

  bind(notBool);
  cmp_eq_imm(ptmp0, ptmp1, T_BYTE, Rscratch1);
  br_cond(notByte, ptmp1);
  sxt1(result, result);
  j(done);

  bind(notByte);
  cmp_eq_imm(ptmp0, ptmp1, T_CHAR, Rscratch1);
  br_cond(notChar, ptmp1);
  zxt2(result, result);
  j(done);

  bind(notChar);
  sxt2(result, result);

  bind(done);
  sxt4(result, result);
}

void InterpreterMacroAssembler::jump_to_entry(address entry) {
  assert(entry != nullptr, "Entry must have been generated by now");
  far_jump(entry);
}

void InterpreterMacroAssembler::check_and_handle_popframe(Register java_thread) {
  if (JvmtiExport::can_pop_frame()) {
    Label L;
    // Initiate popframe handling only if it is not already being
    // processed. If the flag has the popframe_processing bit set,
    // it means that this code is called *during* popframe handling - we
    // don't want to reenter.
    // This method is only called just after the call into the vm in
    // call_VM_base, so the arg registers are available.
    ld4(t2, Address(Rthread, JavaThread::popframe_condition_offset()));
    tbit_z(ptmp0, ptmp1, t2, exact_log2(JavaThread::popframe_pending_bit));
    br_cond(L, ptmp0);
    tbit_nz(ptmp0, ptmp1, t2, exact_log2(JavaThread::popframe_processing_bit));
    br_cond(L, ptmp0);
    // Call Interpreter::remove_activation_preserving_args_entry() to get the
    // address of the same-named entrypoint in the generated interpreter code.
    call_VM_leaf(CAST_FROM_FN_PTR(address, Interpreter::remove_activation_preserving_args_entry));
    jr(Rret);
    bind(L);
  }
}

void InterpreterMacroAssembler::load_earlyret_value(TosState state) {
  ld8(Rscratch2, Address(Rthread, JavaThread::jvmti_thread_state_offset()));
  const Address tos_addr(Rscratch2, JvmtiThreadState::earlyret_tos_offset());
  const Address oop_addr(Rscratch2, JvmtiThreadState::earlyret_oop_offset());
  const Address val_addr(Rscratch2, JvmtiThreadState::earlyret_value_offset());
  switch (state) {
    case atos:
      ld8(Rtos, oop_addr);
      st8(oop_addr, zr);
      verify_oop(Rtos);
      break;
    case ltos:
      ld8(Rtos, val_addr);
      break;
    case btos:  // fall through
    case ztos:  // fall through
    case ctos:  // fall through
    case stos:  // fall through
    case itos:
      ld4s(Rtos, val_addr);
      break;
    case ftos:
      ldfs(Ftos, val_addr);
      break;
    case dtos:
      ldfd(Ftos, val_addr);
      break;
    case vtos:
      /* nothing to do */
      break;
    default:
      ShouldNotReachHere();
  }
  // Clean up tos value in the thread object
  mov_immediate(t2, (int)ilgl);
  st4(tos_addr, t2);
  st4(val_addr, zr);
}

void InterpreterMacroAssembler::check_and_handle_earlyret(Register java_thread) {
  if (JvmtiExport::can_force_early_return()) {
    Label L;
    ld8(t2, Address(Rthread, JavaThread::jvmti_thread_state_offset()));
    beqz(t2, L);  // if thread->jvmti_thread_state() is null then exit

    // Initiate earlyret handling only if it is not already being processed.
    // If the flag has the earlyret_processing bit set, it means that this code
    // is called *during* earlyret handling - we don't want to reenter.
    ld4(t2, Address(t2, JvmtiThreadState::earlyret_state_offset()));
    cmp4_eq_imm(ptmp0, ptmp1, JvmtiThreadState::earlyret_pending, t2);
    br_cond(L, ptmp1);

    // Call Interpreter::remove_activation_early_entry() to get the address of the
    // same-named entrypoint in the generated interpreter code.
    ld8(t2, Address(Rthread, JavaThread::jvmti_thread_state_offset()));
    ld4(t2, Address(t2, JvmtiThreadState::earlyret_tos_offset()));
    call_VM_leaf(CAST_FROM_FN_PTR(address, Interpreter::remove_activation_early_entry), t2);
    jr(Rret);
    bind(L);
  }
}

// Bytecode operands as written in the classfile: big-endian.
void InterpreterMacroAssembler::get_unsigned_2_byte_index_at_bcp(Register reg, int bcp_offset) {
  assert(bcp_offset >= 0, "bcp is still pointing to start of bytecode");
  load_unaligned_be(reg, Rbcp, bcp_offset, 2, t2);
}

// IA-64: cache indices are written back by the rewriter in native (little-
// endian) order, and sit at unaligned addresses, so they are assembled a byte
// at a time -- a misaligned ld2/ld4 would fault.
void InterpreterMacroAssembler::get_cache_index_at_bcp(Register index,
                                                       Register tmp,
                                                       int bcp_offset,
                                                       size_t index_size) {
  assert(bcp_offset > 0, "bcp is still pointing to start of bytecode");
  if (index_size == sizeof(u2)) {
    load_unaligned_le(index, Rbcp, bcp_offset, 2, tmp);
  } else if (index_size == sizeof(u4)) {
    load_unaligned_le(index, Rbcp, bcp_offset, 4, tmp);
  } else if (index_size == sizeof(u1)) {
    ld1(index, Address(Rbcp, bcp_offset));
  } else {
    ShouldNotReachHere();
  }
}

// Load object from cpool->resolved_references(index)
void InterpreterMacroAssembler::load_resolved_reference_at_index(
                                Register result, Register index, Register tmp) {
  assert_different_registers(result, index, tmp);

  get_constant_pool(result);
  // Load pointer for resolved_references[] objArray
  ld8(result, Address(result, ConstantPool::cache_offset()));
  ld8(result, Address(result, ConstantPoolCache::resolved_references_offset()));
  resolve_oop_handle(result, tmp, noreg);
  // Add in the index
  assert(!UseCompressedOops, "IA-64 milestone 1 runs without compressed oops");
  shladd(result, index, LogBytesPerHeapOop, result);
  load_heap_oop(result, Address(result, arrayOopDesc::base_offset_in_bytes(T_OBJECT)), tmp, noreg);
}

void InterpreterMacroAssembler::load_resolved_klass_at_offset(
                                Register cpool, Register index, Register klass, Register temp) {
  shladd(temp, index, LogBytesPerWord, cpool);
  ld2(temp, Address(temp, sizeof(ConstantPool)));                     // temp = resolved_klass_index
  ld8(klass, Address(cpool, ConstantPool::resolved_klasses_offset())); // klass = cpool->_resolved_klasses
  shladd(klass, temp, LogBytesPerWord, klass);
  ld8(klass, Address(klass, Array<Klass*>::base_offset_in_bytes()));
}

// Generate a subtype check: branch to ok_is_subtype if sub_klass is a
// subtype of super_klass.
//
// Args:
//      Rtos: superklass
//      Rsub_klass: subklass
//
// Kills:
//      Rscratch2, Rscratch3, t0, t1, ptmp0/1
void InterpreterMacroAssembler::gen_subtype_check(Register Rsub_klass,
                                                  Label& ok_is_subtype) {
  assert_different_registers(Rsub_klass, Rtos, Rscratch2, Rscratch3);

  // Profile the not-null value's klass.
  profile_typecheck(Rscratch2, Rsub_klass, Rscratch3);

  // Do the check.
  check_klass_subtype(Rsub_klass, Rtos, Rscratch2, Rscratch3, ok_is_subtype);
}

// Java Expression Stack
//
// Resp points at the top element. A pop is one post-incrementing load where
// the width allows it; a push pre-decrements with adds, since IA-64 has no
// pre-decrement addressing.

void InterpreterMacroAssembler::pop_ptr(Register r) {
  ld8_inc(r, Resp, wordSize);
}

void InterpreterMacroAssembler::pop_i(Register r) {
  // Only the low 4 bytes of an int slot are defined (JavaCallArguments
  // writes 4), so load 4 and sign-extend: registers hold ints sign-extended.
  ld4_inc(r, Resp, wordSize);
  sxt4(r, r);
}

void InterpreterMacroAssembler::pop_l(Register r) {
  ld8_inc(r, Resp, 2 * Interpreter::stackElementSize);
}

void InterpreterMacroAssembler::push_ptr(Register r) {
  adds(Resp, -wordSize, Resp);
  Assembler::st8(Resp, r);
}

void InterpreterMacroAssembler::push_i(Register r) {
  adds(Resp, -wordSize, Resp);
  sxt4(r, r);
  Assembler::st8(Resp, r);
}

void InterpreterMacroAssembler::push_l(Register r) {
  // The value goes in the lower-addressed slot; the other is zeroed, as on
  // every port.
  adds(Resp, -wordSize, Resp);
  st8_inc(Resp, zr, -wordSize);
  Assembler::st8(Resp, r);
}

void InterpreterMacroAssembler::pop_f(FloatRegister r) {
  Assembler::ldfs(r, Resp);
  adds(Resp, wordSize, Resp);
}

void InterpreterMacroAssembler::pop_d(FloatRegister r) {
  Assembler::ldfd(r, Resp);
  adds(Resp, 2 * Interpreter::stackElementSize, Resp);
}

void InterpreterMacroAssembler::push_f(FloatRegister r) {
  adds(Resp, -wordSize, Resp);
  Assembler::stfs(Resp, r);
}

void InterpreterMacroAssembler::push_d(FloatRegister r) {
  adds(Resp, -2 * wordSize, Resp);
  Assembler::stfd(Resp, r);
}

void InterpreterMacroAssembler::pop(TosState state) {
  switch (state) {
    case atos:
      pop_ptr();
      verify_oop(Rtos);
      break;
    case btos:  // fall through
    case ztos:  // fall through
    case ctos:  // fall through
    case stos:  // fall through
    case itos:
      pop_i();
      break;
    case ltos:
      pop_l();
      break;
    case ftos:
      pop_f();
      break;
    case dtos:
      pop_d();
      break;
    case vtos:
      /* nothing to do */
      break;
    default:
      ShouldNotReachHere();
  }
}

void InterpreterMacroAssembler::push(TosState state) {
  switch (state) {
    case atos:
      verify_oop(Rtos);
      push_ptr();
      break;
    case btos:  // fall through
    case ztos:  // fall through
    case ctos:  // fall through
    case stos:  // fall through
    case itos:
      push_i();
      break;
    case ltos:
      push_l();
      break;
    case ftos:
      push_f();
      break;
    case dtos:
      push_d();
      break;
    case vtos:
      /* nothing to do */
      break;
    default:
      ShouldNotReachHere();
  }
}

// Helpers for swap and dup
void InterpreterMacroAssembler::load_ptr(int n, Register val) {
  ld8(val, Address(Resp, Interpreter::expr_offset_in_bytes(n)));
}

void InterpreterMacroAssembler::store_ptr(int n, Register val) {
  st8(Address(Resp, Interpreter::expr_offset_in_bytes(n)), val);
}

void InterpreterMacroAssembler::load_float(Address src) {
  ldfs(Ftos, src);
}

void InterpreterMacroAssembler::load_double(Address src) {
  ldfd(Ftos, src);
}

void InterpreterMacroAssembler::check_extended_sp(const char* msg) {
#ifdef ASSERT
  Label L;
  ld8(t2, Address(fp, frame::interpreter_frame_extended_sp_offset * wordSize));
  shladd(t2, t2, LogBytesPerWord, fp);
  beq(sp, t2, L);
  stop(msg);
  bind(L);
#endif
}

void InterpreterMacroAssembler::prepare_to_jump_from_interpreted() {
  // set sender sp
  mov(Rsender_sp, sp);
  // record last_sp, relativized to fp in words
  sub(t2, Resp, fp);
  shr_imm(t2, t2, Interpreter::logStackElementSize);
  st8(Address(fp, frame::interpreter_frame_last_sp_offset * wordSize), t2);
}

// Jump to from_interpreted entry of a call unless single stepping is possible
// in this thread in which case we must call the i2i entry
//
// IA-64: the caller has already put the return address in b0 (riscv puts it
// in ra the same way); this is a jump, not a call.
void InterpreterMacroAssembler::jump_from_interpreted(Register method) {
  prepare_to_jump_from_interpreted();
  if (JvmtiExport::can_post_interpreter_events()) {
    Label run_compiled_code;
    // JVMTI events, such as single-stepping, are implemented partly by avoiding running
    // compiled code in threads for which the event is enabled.  Check here for
    // interp_only_mode if these events CAN be enabled.
    ld4(t2, Address(Rthread, JavaThread::interp_only_mode_offset()));
    beqz(t2, run_compiled_code);
    ld8(t2, Address(method, Method::interpreter_entry_offset()));
    jr(t2);
    bind(run_compiled_code);
  }

  ld8(t2, Address(method, Method::from_interpreted_offset()));
  jr(t2);
}

// The following two routines provide a hook so that an implementation
// can schedule the dispatch in two parts.  amd64 does not do this.
void InterpreterMacroAssembler::dispatch_prolog(TosState state, int step) {
}

void InterpreterMacroAssembler::dispatch_epilog(TosState state, int step) {
  dispatch_next(state, step);
}

// IA-64: there is no dispatch register. The table address is a constant --
// a safepoint copies table *contents* into the active table rather than
// switching tables -- so it is one movl, and the safepoint variant is the
// same movl predicated on the poll bit.
void InterpreterMacroAssembler::dispatch_base(TosState state,
                                              address* table,
                                              bool verifyoop,
                                              bool generate_poll,
                                              Register Rs) {
  assert_different_registers(Rs, t1);
  if (verifyoop && state == atos) {
    verify_oop(Rtos);
  }

  address* const safepoint_table = Interpreter::safept_table(state);
  bool needs_thread_local_poll = generate_poll && table != safepoint_table;

  if (needs_thread_local_poll) {
    NOT_PRODUCT(block_comment("Thread-local Safepoint poll"));
    ld8(t1, Address(Rthread, JavaThread::polling_word_offset()));
    tbit_nz(ptmp0, ptmp1, t1, exact_log2(SafepointMechanism::poll_bit()));
  }
  movl(t1, (address)table);
  if (needs_thread_local_poll) {
    movl(t1, (address)safepoint_table, ptmp0);
  }
  shladd(t1, Rs, LogBytesPerWord, t1);
  Assembler::ld8(t1, t1);
  jr(t1);
}

void InterpreterMacroAssembler::dispatch_only(TosState state, bool generate_poll, Register Rs) {
  dispatch_base(state, Interpreter::dispatch_table(state), true, generate_poll, Rs);
}

void InterpreterMacroAssembler::dispatch_only_normal(TosState state, Register Rs) {
  dispatch_base(state, Interpreter::normal_table(state), true, false, Rs);
}

void InterpreterMacroAssembler::dispatch_only_noverify(TosState state, Register Rs) {
  dispatch_base(state, Interpreter::normal_table(state), false, false, Rs);
}

void InterpreterMacroAssembler::dispatch_next(TosState state, int step, bool generate_poll) {
  // load next bytecode
  if (step != 0) {
    add_imm(Rbcp, Rbcp, step);
  }
  Assembler::ld1(t0, Rbcp);
  dispatch_base(state, Interpreter::dispatch_table(state), true, generate_poll);
}

void InterpreterMacroAssembler::dispatch_via(TosState state, address* table) {
  // load current bytecode
  Assembler::ld1(t0, Rbcp);
  dispatch_base(state, table);
}

// remove activation
//
// Unlock the receiver if this is a synchronized method.
// Unlock any Java monitors from synchronized blocks.
// Apply stack watermark barrier.
// Notify JVMTI.
// Remove the activation from the stack.
//
// If there are locked Java monitors
//    If throw_monitor_exception
//       throws IllegalMonitorStateException
//    Else if install_monitor_exception
//       installs IllegalMonitorStateException
//    Else
//       no error processing
//
// On return b0 holds the return address and sp/Resp the sender's.
void InterpreterMacroAssembler::remove_activation(TosState state,
                                                  bool throw_monitor_exception,
                                                  bool install_monitor_exception,
                                                  bool notify_jvmdi) {
  const Register do_not_unlock = Rscratch4;
  Label unlocked, unlock, no_unlock;

  // get the value of _do_not_unlock_if_synchronized
  const Address do_not_unlock_if_synchronized(Rthread,
    in_bytes(JavaThread::do_not_unlock_if_synchronized_offset()));
  ld1(do_not_unlock, do_not_unlock_if_synchronized);
  st1(do_not_unlock_if_synchronized, zr); // reset the flag

  // get method access flags
  get_method(Rscratch1);
  ld4(Rscratch2, Address(Rscratch1, Method::access_flags_offset()));
  tbit_z(ptmp0, ptmp1, Rscratch2, exact_log2(JVM_ACC_SYNCHRONIZED));
  br_cond(unlocked, ptmp0);

  // Don't unlock anything if the _do_not_unlock_if_synchronized flag
  // is set.
  bnez(do_not_unlock, no_unlock);

  // unlock monitor
  push(state); // save result

  // BasicObjectLock will be first in list, since this is a
  // synchronized method. However, need to check that the object has
  // not been unlocked by an explicit monitorexit bytecode.
  const Address monitor(fp, frame::interpreter_frame_initial_sp_offset *
                        wordSize - (int) sizeof(BasicObjectLock));
  // We use c_rarg1 so that if we go slow path it will be the correct
  // register for unlock_object to pass to VM directly
  lea(c_rarg1, monitor); // address of first monitor

  ld8(Rtos, Address(c_rarg1, BasicObjectLock::obj_offset()));
  bnez(Rtos, unlock);

  pop(state);
  if (throw_monitor_exception) {
    // Entry already unlocked, need to throw exception
    call_VM(noreg, CAST_FROM_FN_PTR(address,
                                    InterpreterRuntime::throw_illegal_monitor_state_exception));
    should_not_reach_here();
  } else {
    // Monitor already unlocked during a stack unroll. If requested,
    // install an illegal_monitor_state_exception.  Continue with
    // stack unrolling.
    if (install_monitor_exception) {
      call_VM(noreg, CAST_FROM_FN_PTR(address,
                                      InterpreterRuntime::new_illegal_monitor_state_exception));
    }
    j(unlocked);
  }

  bind(unlock);
  unlock_object(c_rarg1);
  pop(state);

  // Check that for block-structured locking (i.e., that all locked
  // objects has been unlocked)
  bind(unlocked);

  // Rtos: Might contain return value

  // Check that all monitors are unlocked
  {
    Label loop, exception, entry, restart;
    const int entry_size = frame::interpreter_frame_monitor_size_in_bytes();
    const Address monitor_block_top(
      fp, frame::interpreter_frame_monitor_block_top_offset * wordSize);
    const Address monitor_block_bot(
      fp, frame::interpreter_frame_initial_sp_offset * wordSize);
    const Register bottom = Rscratch3;

    bind(restart);
    // We use c_rarg1 so that if we go slow path it will be the correct
    // register for unlock_object to pass to VM directly
    ld8(c_rarg1, monitor_block_top); // derelativize pointer
    shladd(c_rarg1, c_rarg1, LogBytesPerWord, fp);
    // c_rarg1 points to current entry, starting with top-most entry

    lea(bottom, monitor_block_bot);  // points to word before bottom of
                                     // monitor block

    j(entry);

    // Entry already locked, need to throw exception
    bind(exception);

    if (throw_monitor_exception) {
      // Throw exception
      MacroAssembler::call_VM(noreg,
                              CAST_FROM_FN_PTR(address, InterpreterRuntime::
                                               throw_illegal_monitor_state_exception));

      should_not_reach_here();
    } else {
      // Stack unrolling. Unlock object and install illegal_monitor_exception.
      // Unlock does not block, so don't have to worry about the frame.
      // We don't have to preserve c_rarg1 since we are going to throw an exception.

      push(state);
      unlock_object(c_rarg1);
      pop(state);

      if (install_monitor_exception) {
        call_VM(noreg, CAST_FROM_FN_PTR(address,
                                        InterpreterRuntime::
                                        new_illegal_monitor_state_exception));
      }

      j(restart);
    }

    bind(loop);
    // check if current entry is used
    ld8(t2, Address(c_rarg1, BasicObjectLock::obj_offset()));
    bnez(t2, exception);

    adds(c_rarg1, entry_size, c_rarg1); // otherwise advance to next entry
    bind(entry);
    bne(c_rarg1, bottom, loop); // check if bottom reached if not at bottom then check this entry
  }

  bind(no_unlock);

  JFR_ONLY(enter_jfr_critical_section();)

  // The below poll is for the stack watermark barrier. It allows fixing up frames lazily,
  // that would normally not be safe to use. Such bad returns into unsafe territory of
  // the stack, will call InterpreterRuntime::at_unwind.
  Label slow_path;
  Label fast_path;
  safepoint_poll(slow_path, true /* at_return */, false /* acquire */, false /* in_nmethod */);
  j(fast_path);

  bind(slow_path);
  push(state);
  set_last_Java_frame(Resp, fp, (address)pc(), t2);
  super_call_VM_leaf(CAST_FROM_FN_PTR(address, InterpreterRuntime::at_unwind), Rthread);
  reset_last_Java_frame(true);
  pop(state);
  bind(fast_path);

  // JVMTI support. Make sure the safepoint poll test is issued prior.
  if (notify_jvmdi) {
    notify_method_exit(state, NotifyJVMTI); // preserve TOSCA
  } else {
    notify_method_exit(state, SkipNotifyJVMTI); // preserve TOSCA
  }

  // remove activation
  // get sender esp
  const Register sender_esp = Rscratch1;
  ld8(sender_esp, Address(fp, frame::interpreter_frame_sender_sp_offset * wordSize));
  if (StackReservedPages > 0) {
    // testing if reserved zone needs to be re-enabled
    Label no_reserved_zone_enabling;

    // check if already enabled - if so no re-enabling needed
    assert(sizeof(StackOverflow::StackGuardState) == 4, "unexpected size");
    ld4(t2, Address(Rthread, JavaThread::stack_guard_state_offset()));
    cmp4_eq_imm(ptmp0, ptmp1, StackOverflow::stack_guard_enabled, t2);
    br_cond(no_reserved_zone_enabling, ptmp0);

    // look for an overflow into the stack reserved zone, i.e.
    // interpreter_frame_sender_sp <= JavaThread::reserved_stack_activation
    ld8(t2, Address(Rthread, JavaThread::reserved_stack_activation_offset()));
    bleu(sender_esp, t2, no_reserved_zone_enabling);

    JFR_ONLY(leave_jfr_critical_section();)

    call_VM_leaf(
      CAST_FROM_FN_PTR(address, SharedRuntime::enable_stack_reserved_zone), Rthread);
    call_VM(noreg, CAST_FROM_FN_PTR(address,
                                    InterpreterRuntime::throw_delayed_StackOverflowError));
    should_not_reach_here();

    bind(no_reserved_zone_enabling);
  }

  // remove frame anchor; leaves the return address in b0
  leave();

  JFR_ONLY(leave_jfr_critical_section();)

  // restore sender esp
  mov(Resp, sender_esp);

  // If we're returning to interpreted code we will shortly be
  // adjusting SP to allow some space for ESP.  If we're returning to
  // compiled code the saved sender SP was saved in sender_sp, so this
  // restores it.
  //
  // IA-64: nothing is called between here and the caller's
  // restore_sp_after_call, so the psABI scratch area below this sp
  // overlapping the caller's expression stack is harmless.
  and_imm(sp, -16, Resp);
}

#if INCLUDE_JFR
void InterpreterMacroAssembler::enter_jfr_critical_section() {
  const Address sampling_critical_section(Rthread, in_bytes(SAMPLING_CRITICAL_SECTION_OFFSET_JFR));
  mov_immediate(t2, 1);
  st1(sampling_critical_section, t2);
}

void InterpreterMacroAssembler::leave_jfr_critical_section() {
  const Address sampling_critical_section(Rthread, in_bytes(SAMPLING_CRITICAL_SECTION_OFFSET_JFR));
  st1(sampling_critical_section, zr);
}
#endif // INCLUDE_JFR

// Lock object
//
// Args:
//      c_rarg1: BasicObjectLock to be used for locking
//
// IA-64 milestone 1: always the runtime path. InterpreterRuntime::monitorenter
// implements every LockingMode, so this is correct (if slow) under the
// default LM_LIGHTWEIGHT; Zero does the same.
void InterpreterMacroAssembler::lock_object(Register lock_reg)
{
  assert(lock_reg == c_rarg1, "The argument is only for looks. It must be c_rarg1");
  call_VM(noreg, CAST_FROM_FN_PTR(address, InterpreterRuntime::monitorenter), lock_reg);
}

// Unlocks an object. Used in monitorexit bytecode and
// remove_activation.  Throws an IllegalMonitorException if object is
// not locked by current thread.
//
// Args:
//      c_rarg1: BasicObjectLock for lock
void InterpreterMacroAssembler::unlock_object(Register lock_reg)
{
  assert(lock_reg == c_rarg1, "The argument is only for looks. It must be rarg1");
  save_bcp(); // Save in case of exception
  call_VM_leaf(CAST_FROM_FN_PTR(address, InterpreterRuntime::monitorexit), lock_reg);
}

// ---- profiling ----------------------------------------------------------------
//
// ProfileInterpreter is false without a compiler, which is every milestone-1
// build. The callers in the template table test ProfileInterpreter before
// using these; refuse loudly at generation time if that ever changes.

#define IA64_NO_PROFILING() \
  guarantee(!ProfileInterpreter, "IA-64: interpreter profiling arrives with C1")

void InterpreterMacroAssembler::test_method_data_pointer(Register mdp, Label& zero_continue) { IA64_NO_PROFILING(); }
void InterpreterMacroAssembler::set_method_data_pointer_for_bcp() { IA64_NO_PROFILING(); }
void InterpreterMacroAssembler::verify_method_data_pointer() { IA64_NO_PROFILING(); }
void InterpreterMacroAssembler::set_mdp_data_at(Register mdp_in, int constant, Register value) { IA64_NO_PROFILING(); }
void InterpreterMacroAssembler::increment_mdp_data_at(Register mdp_in, int constant) { IA64_NO_PROFILING(); }
void InterpreterMacroAssembler::increment_mdp_data_at(Register mdp_in, Register index, int constant) { IA64_NO_PROFILING(); }
void InterpreterMacroAssembler::set_mdp_flag_at(Register mdp_in, int flag_constant) { IA64_NO_PROFILING(); }
void InterpreterMacroAssembler::test_mdp_data_at(Register mdp_in, int offset, Register value,
                                                 Register test_value_out, Label& not_equal_continue) { IA64_NO_PROFILING(); }
void InterpreterMacroAssembler::update_mdp_by_offset(Register mdp_in, int offset_of_disp) { IA64_NO_PROFILING(); }
void InterpreterMacroAssembler::update_mdp_by_offset(Register mdp_in, Register reg, int offset_of_disp) { IA64_NO_PROFILING(); }
void InterpreterMacroAssembler::update_mdp_by_constant(Register mdp_in, int constant) { IA64_NO_PROFILING(); }
void InterpreterMacroAssembler::update_mdp_for_ret(Register return_bci) { IA64_NO_PROFILING(); }

// The profile_* entry points are called unconditionally by some templates
// and test ProfileInterpreter themselves, as on riscv: they emit nothing.
void InterpreterMacroAssembler::profile_taken_branch(Register mdp, Register bumped_count) { IA64_NO_PROFILING(); }
void InterpreterMacroAssembler::profile_not_taken_branch(Register mdp) { IA64_NO_PROFILING(); }
void InterpreterMacroAssembler::profile_call(Register mdp) { IA64_NO_PROFILING(); }
void InterpreterMacroAssembler::profile_final_call(Register mdp) { IA64_NO_PROFILING(); }
void InterpreterMacroAssembler::profile_virtual_call(Register receiver, Register mdp,
                                                     Register reg2, bool receiver_can_be_null) { IA64_NO_PROFILING(); }
void InterpreterMacroAssembler::profile_ret(Register return_bci, Register mdp) { IA64_NO_PROFILING(); }
void InterpreterMacroAssembler::profile_null_seen(Register mdp) { IA64_NO_PROFILING(); }
void InterpreterMacroAssembler::profile_typecheck(Register mdp, Register klass, Register temp) { IA64_NO_PROFILING(); }
void InterpreterMacroAssembler::profile_typecheck_failed(Register mdp) { IA64_NO_PROFILING(); }
void InterpreterMacroAssembler::profile_switch_default(Register mdp) { IA64_NO_PROFILING(); }
void InterpreterMacroAssembler::profile_switch_case(Register index, Register mdp, Register reg2) { IA64_NO_PROFILING(); }
void InterpreterMacroAssembler::profile_obj_type(Register obj, const Address& mdo_addr, Register tmp) { IA64_NO_PROFILING(); }
void InterpreterMacroAssembler::profile_arguments_type(Register mdp, Register callee, Register tmp, bool is_virtual) { IA64_NO_PROFILING(); }
void InterpreterMacroAssembler::profile_return_type(Register mdp, Register ret, Register tmp) { IA64_NO_PROFILING(); }
void InterpreterMacroAssembler::profile_parameters_type(Register mdp, Register tmp1, Register tmp2, Register tmp3) { IA64_NO_PROFILING(); }

#undef IA64_NO_PROFILING

// ---- JVMTI / dtrace -------------------------------------------------------------

void InterpreterMacroAssembler::notify_method_entry() {
  // Whenever JVMTI is interp_only_mode, method entry/exit events are sent to
  // track stack depth.  If it is possible to enter interp_only_mode we add
  // the code to check if the event should be sent.
  if (JvmtiExport::can_post_interpreter_events()) {
    Label L;
    ld4(t2, Address(Rthread, JavaThread::interp_only_mode_offset()));
    beqz(t2, L);
    call_VM(noreg, CAST_FROM_FN_PTR(address,
                                    InterpreterRuntime::post_method_entry));
    bind(L);
  }

  if (DTraceMethodProbes) {
    get_method(c_rarg1);
    call_VM_leaf(CAST_FROM_FN_PTR(address, SharedRuntime::dtrace_method_entry),
                 Rthread, c_rarg1);
  }

  // RedefineClasses() tracing support for obsolete method entry
  if (log_is_enabled(Trace, redefine, class, obsolete)) {
    get_method(c_rarg1);
    call_VM_leaf(
      CAST_FROM_FN_PTR(address, SharedRuntime::rc_trace_method_entry),
      Rthread, c_rarg1);
  }
}

void InterpreterMacroAssembler::notify_method_exit(
    TosState state, NotifyMethodExitMode mode) {
  // Whenever JVMTI is interp_only_mode, method entry/exit events are sent to
  // track stack depth.  If it is possible to enter interp_only_mode we add
  // the code to check if the event should be sent.
  if (mode == NotifyJVMTI && JvmtiExport::can_post_interpreter_events()) {
    Label L;
    // Note: frame::interpreter_frame_result has a dependency on how the
    // method result is saved across the call to post_method_exit. If this
    // is changed then the interpreter_frame_result implementation will
    // need to be updated too.

    // template interpreter will leave the result on the top of the stack.
    push(state);
    ld4(t2, Address(Rthread, JavaThread::interp_only_mode_offset()));
    beqz(t2, L);
    call_VM(noreg,
            CAST_FROM_FN_PTR(address, InterpreterRuntime::post_method_exit));
    bind(L);
    pop(state);
  }

  if (DTraceMethodProbes) {
    push(state);
    get_method(c_rarg1);
    call_VM_leaf(CAST_FROM_FN_PTR(address, SharedRuntime::dtrace_method_exit),
                 Rthread, c_rarg1);
    pop(state);
  }
}

// Jump if ((*counter_addr += increment) & mask) == 0
void InterpreterMacroAssembler::increment_mask_and_jump(Address counter_addr,
                                                        int increment, Address mask,
                                                        Register tmp1, Register tmp2,
                                                        bool preloaded, Label* where) {
  if (!preloaded) {
    ld4(tmp1, counter_addr);
  }
  add_imm(tmp1, tmp1, increment);
  st4(counter_addr, tmp1);
  ld4(tmp2, mask);
  and_(tmp1, tmp1, tmp2);
  cmp4_eq(ptmp0, ptmp1, tmp1, zr);
  br_cond(*where, ptmp0);
}

// ---- calls into the VM ------------------------------------------------------------
//
// IA-64: Rlocals, Rmethod and Rcpool are caller-saved here (riscv keeps them in
// callee-saved registers), so both kinds of call reload them afterwards.

void InterpreterMacroAssembler::restore_interpreter_state_after_call() {
  restore_locals();
  restore_method();
  restore_constant_pool_cache();
}

void InterpreterMacroAssembler::call_VM_leaf_base(address entry_point,
                                                  int number_of_arguments) {
  // interpreter specific
  //
  // Rbcp is preserved by the C ABI (r6), and no blocking or GC can happen in
  // a leaf call, so it needs neither saving nor reloading.
#ifdef ASSERT
  {
    Label L;
    ld8(t2, Address(fp, frame::interpreter_frame_last_sp_offset * wordSize));
    beqz(t2, L);
    stop("InterpreterMacroAssembler::call_VM_leaf_base:"
         " last_sp isn't null");
    bind(L);
  }
#endif /* ASSERT */
  // super call
  MacroAssembler::call_VM_leaf_base(entry_point, number_of_arguments);
  restore_interpreter_state_after_call();
}

void InterpreterMacroAssembler::call_VM_base(Register oop_result,
                                             Register java_thread,
                                             Register last_java_sp,
                                             address  entry_point,
                                             int      number_of_arguments,
                                             bool     check_exceptions) {
  // interpreter specific
  //
  // bcp must be saved/restored since it may change due to GC.
  save_bcp();
#ifdef ASSERT
  {
    Label L;
    ld8(t2, Address(fp, frame::interpreter_frame_last_sp_offset * wordSize));
    beqz(t2, L);
    stop("InterpreterMacroAssembler::call_VM_base:"
         " last_sp isn't null");
    bind(L);
  }
#endif /* ASSERT */
  // super call
  MacroAssembler::call_VM_base(oop_result, noreg, last_java_sp,
                               entry_point, number_of_arguments,
                               check_exceptions);
  // interpreter specific
  restore_bcp();
  restore_interpreter_state_after_call();
}

// ---- constant pool cache entries ----------------------------------------------------

void InterpreterMacroAssembler::load_resolved_indy_entry(Register cache, Register index) {
  // Get index out of bytecode pointer, get_cache_entry_pointer_at_bcp
  // register "cache" is trashed in next ld, so lets use it as a temporary register
  get_cache_index_at_bcp(index, cache, 1, sizeof(u4));
  // Get address of invokedynamic array
  ld8(cache, Address(Rcpool, in_bytes(ConstantPoolCache::invokedynamic_entries_offset())));
  // Scale the index to be the entry index * sizeof(ResolvedIndyEntry)
  shl_imm(index, index, log2i_exact(sizeof(ResolvedIndyEntry)));
  adds(cache, Array<ResolvedIndyEntry>::base_offset_in_bytes(), cache);
  add(cache, cache, index);
}

void InterpreterMacroAssembler::load_field_entry(Register cache, Register index, int bcp_offset) {
  // Get index out of bytecode pointer
  get_cache_index_at_bcp(index, cache, bcp_offset, sizeof(u2));
  // Scale the index to be the entry index * sizeof(ResolvedFieldEntry)
  mul_imm(index, index, sizeof(ResolvedFieldEntry), cache);
  // Get address of field entries array
  ld8(cache, Address(Rcpool, ConstantPoolCache::field_entries_offset()));
  adds(cache, Array<ResolvedFieldEntry>::base_offset_in_bytes(), cache);
  add(cache, cache, index);
  // Prevents stale data from being read after the bytecode is patched to the fast bytecode
  membar(MacroAssembler::LoadLoad);
}

void InterpreterMacroAssembler::get_method_counters(Register method,
                                                    Register mcs, Label& skip) {
  assert(method == Rmethod, "reloaded from the frame after the call, so it must be Rmethod");
  Label has_counters;
  ld8(mcs, Address(method, Method::method_counters_offset()));
  bnez(mcs, has_counters);
  call_VM(noreg, CAST_FROM_FN_PTR(address,
          InterpreterRuntime::build_method_counters), method);
  ld8(mcs, Address(method, Method::method_counters_offset()));
  beqz(mcs, skip); // No MethodCounters allocated, OutOfMemory
  bind(has_counters);
}

void InterpreterMacroAssembler::load_method_entry(Register cache, Register index, int bcp_offset) {
  // Get index out of bytecode pointer
  get_cache_index_at_bcp(index, cache, bcp_offset, sizeof(u2));
  // Scale the index to be the entry index * sizeof(ResolvedMethodEntry)
  mul_imm(index, index, sizeof(ResolvedMethodEntry), cache);

  // Get address of method entries array
  ld8(cache, Address(Rcpool, ConstantPoolCache::method_entries_offset()));
  adds(cache, Array<ResolvedMethodEntry>::base_offset_in_bytes(), cache);
  add(cache, cache, index);
}

#ifdef ASSERT
void InterpreterMacroAssembler::verify_access_flags(Register access_flags, uint32_t flag,
                                                    const char* msg, bool stop_by_hit) {
  Label L;
  tbit_nz(ptmp0, ptmp1, access_flags, exact_log2(flag));
  if (stop_by_hit) {
    br_cond(L, ptmp1);    // bit clear: fine
  } else {
    br_cond(L, ptmp0);    // bit set: fine
  }
  stop(msg);
  bind(L);
}

void InterpreterMacroAssembler::verify_frame_setup() {
  Label L;
  const Address monitor_block_top(fp, frame::interpreter_frame_monitor_block_top_offset * wordSize);
  ld8(t2, monitor_block_top);
  shladd(t2, t2, LogBytesPerWord, fp);
  beq(Resp, t2, L);
  stop("broken stack frame setup in interpreter");
  bind(L);
}
#endif
